attendence/urls.py
from django.urls import path, include

from attendence import views

app_name = 'attendence'
urlpatterns = [
    path('', views.IndexTemplateView.as_view(), name='index'),

    path('student/', views.StudentListView.as_view(), name='student-list'),
    path('student/create/', views.StudentCreateView.as_view(), name='student-create'),
    path('student/<slug:slug>/view/', views.StudentDetailView.as_view(), name='student-detail'),

    path('semester/', views.SemesterListView.as_view(), name='semester-list'),
    path('semester/<int:pk>/view/', views.SemesterDetailView.as_view(), name='semester-detail'),

    path('course/', views.CourseListView.as_view(), name='course-list'),
    path('course/<int:pk>/view/', views.CourseDetailView.as_view(), name='course-detail'),
]

website/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('attendence/', include('attendence.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='attendence/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendence/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
import datetime

# Create your models here.

class Student(models.Model):
    # user = models.onetoonefield(
    #     user,
    #     on_delete=models.cascade,
    #     related_name='profile_student',
    # )
    name = models.CharField(
        default='',
        max_length=100,
    )
    email = models.CharField(
        default='',
        max_length=100,
    )
    roll_number = models.CharField(
        default='',
        max_length=30,
        unique=True,
    )
    year_of_enrollment = models.IntegerField(
        default=2020,
    )
    program = models.CharField(
        default='BTech',
        max_length=30,
    )
    status = models.CharField(
        blank=True,
        default='Active',
        max_length=30,
    )
    gender = models.CharField(
        default='male',
        max_length=30,
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('attendence:student-detail', kwargs={'slug': self.roll_number})

class Faculty(models.Model):
    CATEGORY_CHOICES = (
        ('',''),
        ('fulltime','Full Time'),
        ('parttime','Part Time'),
        ('guest','Guest'),
    )
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile',
    )
    name = models.CharField(
        default='',
        max_length=100,
    )
    faculty_id = models.CharField(
        default='',
        max_length=30,
        unique=True,
        verbose_name='Faculty ID',
    )
    category = models.CharField(
        choices=CATEGORY_CHOICES,
        max_length=50,
        default='',
    )
    department = models.CharField(
        default='',
        max_length=50,
        verbose_name='Department',
    )
    active = models.BooleanField(default=True)
    status = models.CharField(
        blank=True,
        default='Active',
        max_length=30,
    )

    def __str__(self):
        return '{} ({})'.format(self.name, self.faculty_id)

class Semester(models.Model):
    name = models.CharField(
        max_length=30,
        default='',
    )
    academic_year = models.IntegerField(
        default=2020,
    )
    date_start = models.DateField(
        null=True,
    )
    date_end = models.DateField(
        null=True,
    )
    status = models.CharField(
        default='Active',
        max_length=30,
    )
    students_enrolled = models.ManyToManyField(
        'Student',
        blank=True,
        related_name='semsters',
    )

    def get_absolute_url(self):
        return reverse('attendence:semester-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

class CourseDetail(models.Model):
    """ This is equivalent for CourseMaster class.
    """
    DAY_CHOICE = (
        ('',''),
        ('0','Monday'),
        ('1','Tuesday'),
        ('2','Wednesday'),
        ('3','Thursday'),
        ('4','Friday'),
        ('5','Saturday'),
        ('6','Sunday'),
    )
    TERM_CHOICES = (
        ('',''),
        ('spring','Spring'),
        ('monsoon','Monsoon'),
        ('summer','Summer'),
    )

    name = models.CharField(
        max_length=100,
        default='',
    )
    code = models.CharField(
        max_length=20,
        default='',
        unique=True,
    )
    credit = models.PositiveIntegerField(
        default=0,
    )
    term = models.CharField(
        choices=TERM_CHOICES,
        max_length=10,
        default='',
    )
    day1 = models.CharField(
        choices=DAY_CHOICE,
        max_length=10,
        default='',
        blank=True,
    )
    day2 = models.CharField(
        choices=DAY_CHOICE,
        max_length=10,
        default='',
        blank=True,
    )

    def __str__(self):
        return '{} ({})'.format(self.name, self.credit)


class Course(models.Model):
    """ This is the equivalent class for CourseForSem.
    """
    course_detail = models.ForeignKey(
        'CourseDetail',
        null=True,
        on_delete=models.CASCADE,
        related_name='courses',
    )
    semester = models.ForeignKey(
        'Semester',
        null=True,
        on_delete=models.CASCADE,
        related_name='courses',
    )
    date_start = models.DateField(
        null=True,
    )
    date_end = models.DateField(
        null=True,
    )
    students = models.ManyToManyField(
        'Student',
        blank=True,
        related_name='courses',
    )
    faculty_primary = models.ForeignKey(
        'Faculty',
        null=True,
        on_delete=models.CASCADE,
        related_name='courses',
    )
    faculty_secondary = models.ManyToManyField(
        'Faculty',
        blank=True,
        related_name='courses_secondary',
    )

    def __str__(self):
        if self.course_detail:
            return self.course_detail.name
        else:
            return str(self.id)

    @property
    def name(self):
        return self.course_detail.name

    def get_absolute_url(self):
        return reverse('attendence:course-detail', kwargs={'pk': self.pk})

class Class(models.Model):
    """Each entry in calender class contains  the record for a
    course runned on a particular date
    """
    course = models.ForeignKey(
        'Course',
        on_delete=models.CASCADE,
        related_name='course_entries',
    )
    date = models.DateField(
        default=datetime.date.today,
    )
    # TODO: modify to include the various statues in choices
    status = models.CharField(
        default='Active',
        max_length=30,
    )
    approved = models.BooleanField(default=False)
    students_attended = models.ManyToManyField(
        'Student',
        blank=True,
        related_name='course_entries',
    )

attendence/views.py
from datetime import datetime, timedelta
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.dates import MonthArchiveView, DayArchiveView
from django.views.decorators.csrf import csrf_exempt

from attendence.models import *

# Create your views here.

class IndexTemplateView(TemplateView):
    template_name = 'attendence/index.html'

class StudentListView(ListView):
    model = Student
    navigation = 'student'

class StudentCreateView(CreateView):
    model = Student
    template_name_suffix = '_create_form'
    fields = '__all__'

class StudentDetailView(DetailView):
    model = Student
    slug_field = 'roll_number'

class SemesterListView(ListView):
    model = Semester
    navigation = 'semester'

class SemesterDetailView(DetailView):
    model = Semester

class CourseDetailView(LoginRequiredMixin, DetailView):
    model = Course

class CourseListView(ListView):
    model = Course
    navigation = 'course'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(faculty_primary__user=self.request.user)
        return queryset

attendence/templates/attendence/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		{% include "attendence/head_content.html" %}
		<title>{% block title %}Attendence Portal{% endblock %}</title>
		<script>
			$(function() {
				$("[id^=id_date]").datepicker({
					dateFormat: "yy-mm-dd"
				});
			});
		</script>
		<style>
		    .errorlist {
		        margin-bottom: .25rem;
		        margin-left: 0px;
		        padding-left: 0px;
		        list-style: none;
		    }
		</style>
		{% block custom_css %}{% endblock %}
		{% block custom_js %}{% endblock %}
	</head>
	<body>
		{% block navbar %}
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a class="navbar-brand" href="{% url 'attendence:index' %}">Attendence Portal</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMarkup" aria-controls="navbarMarkup" aria-expanded="false" aria-label="Toggle Navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarMarkup">
				<div class="navbar-nav mr-auto">
					<a class="nav-item nav-link {% if view.navigation == 'semester' %}active{% endif %}" href="{% url 'attendence:semester-list' %}">Semesters</a>
					<a class="nav-item nav-link {% if view.navigation == 'course' %}active{% endif %}" href="{% url 'attendence:course-list' %}">Courses</a>
					<a class="nav-item nav-link {% if view.navigation == 'student' %}active{% endif %}" href="{% url 'attendence:student-list' %}">Students</a>
				</div>
				{% block custom_navbar %}{% endblock %}
				<div class="navbar-nav">
					{% if request.user.is_authenticated %}
					<span class="mr-3">Hi, {{ request.user.profile.name }}</span>
					<a class="btn btn-outline-danger btn-sm" href="{% url 'logout' %}">Logout</a>
					{% else %}
					<a class="btn btn-sm btn-outline-success" href="{% url 'login' %}">Login</a>
					{% endif %}
					<a class="btn btn-sm btn-outline-primary" href="{% url 'admin:index' %}">Admin</a>
				</div>
			</div>
		</nav>
		{% endblock %}
		<main>
		{% block main_content %}{% endblock %}
		</main>
	</body>
</html>

attendence/templates/attendence/course_detail.html
{% extends 'attendence/base.html' %}
{% load static %}

{% block main_content %}
<div class="container">
    Details for Course - {{ course.name }} ({{ course.semester.name }})<br>
    Primary Faculty - {{ course.faculty_primary }}
    <ul>
        Secondary Faculty:<br>
        {% for faculty in course.faculty_secondary.all %}
        {{ faculty.name }}
        {% empty %}
        No Seconday Faculty
        {% endfor %}
    </ul>
    <br><br>
    <ul>
        Students Enrolled in this course
        {% for student in course.students.all %}
        <li>{{ student.name }}</li>
        {% empty %}
        <li>No Student Enrolled</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

attendence/templates/attendence/course_list.html
{% extends 'attendence/base.html' %}
{% load static %}

{% block main_content %}
<div class="container">
    <div class="h3">List of all courses</div>
    {% for course in course_list %}
    <a href="{{ course.get_absolute_url }}">{{ course.name }}</a>
    {% empty %}
    No courses found
    {% endfor %}
</div>
{% endblock %}

attendence/templates/attendence/head_content.html
{% load static %}

{# JQuery #}
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

{# Popper.js #}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

{# JQuery UI #}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

{# Bootstrap #}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{# Font Awesome #}
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

{# Moment.js #}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

attendence/templates/attendence/index.html
{% extends 'attendence/base.html' %}
{% load static %}

{% block main_content %}
<div class="container">
	Welcome
</div>
{% endblock %}

attendence/templates/attendence/login.html
{% extends 'attendence/base.html' %}
{% load static %}

{% block main_content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

attendence/templates/attendence/semester_detail.html
{% extends 'attendence/base.html' %}
{% load static %}

{% block main_content %}
<div class="container">
    Details for Semester - {{ semester.name }}<br>
    Year - {{ semester.academic_year }}<br><br>
    <ul>
        Courses offered in This Semester:<br>
        {% for course in semester.courses.all %}
        <a href="{{ course.get_absolute_url }}">{{ course.name }}</a>
        {% empty %}
        No corses registered for this Semester
        {% endfor %}
    </ul>
</div>
{% endblock %}

attendence/templates/attendence/semester_list.html
{% extends 'attendence/base.html' %}
{% load static %}

{% block main_content %}
<div class="container">
    <div class="h3">List of all Semesters</div>
    {% for semester in semester_list %}
    <a href="{{ semester.get_absolute_url }}">{{ semester.name }}</a>
    {% empty %}
    No semester found
    {% endfor %}
</div>
{% endblock %}

attendence/templates/attendence/student_create_form.html
{% extends 'attendence/base.html' %}
{% load static %}
{% load add_attr %}

{% block main_content %}
<div class="container">
    <h2>Create New Student</h2>
    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
			<div class="form-group row">
				<label for="{{ field.id_for_label }}" class="col-4 col-form-label">{{ field.label }}</label>
				<div class="col-8">
					{{ field|add_attr:"form-control" }}
					{% if field.help_text %}
					<small class="form-text text-muted">{{ field.help_text }}</small>
					{% endif %}
				</div>
			</div>
			{% endfor %}
			<!-- <div class="form-group row d-flex justify-content-center">
				<button type="submit" class="btn btn-outline-success w-50 d-none" id="btn-submit">Update</button>
			</div> -->
            <button type="submit" class="btn btn-success">Create</button>
        </form>
    </div>
</div>
{% endblock %}

attendence/templates/attendence/student_detail.html
{% extends 'attendence/base.html' %}
{% load static %}

{% block main_content %}
<div class="container">
    Details for Student - {{ student.name }} ({{ student.roll_number }})<br>
    year of enrollment = {{ student.year_of_enrollment }}<br>
    program = {{ student.program }}<br>
    status = {{ student.status }}<br>
    gender = {{ student.gender }}<br>
</div>
{% endblock %}

attendence/templates/attendence/student_list.html
{% extends 'attendence/base.html' %}
{% load static %}

{% block main_content %}
<div class="container">
    <div class="h3">List of all Students</div>
    <div>
        <a href="{% url 'attendence:student-create' %}" class="btn btn-primary">Add New Student</a>
    </div>
    {% for student in student_list %}
    <a href="{{ student.get_absolute_url }}">{{ student.name }}</a><br>
    {% empty %}
    No Students Registered
    {% endfor %}
</div>
{% endblock %}